version: 2.1
commands:
  print_pipeline_id:
    description: "Print out an ID number"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
      - print_pipeline_id
      - run: yarn build > ~/
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/
      - run: yarn test:e2e
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn audit

workflows:
  covid-19-ci:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
